### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by Behzad-Elhamian** [airmobisim/AirMobiSim#1]
I downloaded the file you posted on the Airmobisim official site and put it in Oracle virtualbox and ran it, but there is a problem, the poetry library is not installed, but when I manually install Python 3.9 and run the shell, the library is installed, but at the end it returns to another error. I would appreciate it if you could help me with this
Grateful
![Screenshot (9)](https://user-images.githubusercontent.com/56151161/205428005-484ff14b-8551-44f6-bfad-c172c6219040.png)
![Screenshot_20221127_015630](https://user-images.githubusercontent.com/56151161/205428008-5e5a69e9-d486-4f59-8878-bbb42cd57d9f.png)

**Comment by thardes2** [comment]
Fixed with 9029c61 and bb4059e
