### ISSUE TITLE
Error in Build program

### ISSUE THREAD

**Issue by Behzad-Elhamian** [airmobisim/AirMobiSim#2]
Dear Tobias, I applied your changes commit, the building program only gives this error, I even put this line in .bashrc and .zhrc, I built it again, but the program gives the same error again.
Grateful
![Screenshot (51)](https://user-images.githubusercontent.com/56151161/209807482-0dacb75c-b5c8-41f7-877f-c4694c4ee369.png)
![Screenshot (52)](https://user-images.githubusercontent.com/56151161/209807486-ba581c72-06d2-4e67-bf13-274917d4e9ff.png)
![Screenshot (53)](https://user-images.githubusercontent.com/56151161/209807488-3fd115f8-71c0-4b91-9d29-6a474e1d6dc1.png)

**Comment by thardes2** [comment]
The problem cannot be reproduced with the current VM
